"""empty message

Revision ID: 77419c759a9b
Revises: 
Create Date: 2021-03-15 19:21:32.397149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77419c759a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('category', 'questions', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
